print('+---------------------------------------------------------------------+')
print('|                                                                     |')
print('|                                                        20.09.2025   |')
print('|                                                     Türkiye, E    |')
print('|         Dear Self,                                                  |')
print('|                                                                     |')
print('|         Build the platform you always dreamed of —                  |')
print('|         the one you wish existed when you started.                  |')
print('|         Give more than you take.                                    |')
print('|         Care > capital.                                             |')
print('|         Five-second funerals for all the Ls.                        |')
print('|         And always get back up.                                     |')
print('|                                                                     |')
print('|                                                 Kim Han            |')
print('|                                                                     |')
print('+---------------------------------------------------------------------+')
